### PR TITLE
Application structure and relationships

### PR DESCRIPTION
**Pull request by avraham1992**

### CODE REVIEW

**Comment by AvivLiberman** [comment]
@avraham1992 

1. Did you check if the project is running and working?
2. You should squash your commits
3. You should fix Flake8 errors

**Review by AvivLiberman — CHANGES_REQUESTED** [review]
@avraham1992 

1. Did you check that the project is running and working?
2. You should squash your commits 
3. You should fix Flake8 errors

**Comment by AvivLiberman** [comment]
@mgold1234 @natifridman @kobihk Can you please approve that's new folder and apps structure?

**Comment by orzionpour** [comment]
1. Commits should be squashed.
2. I would add to the description an explanation about what's going on in here.
Maybe something like 
"Created Django apps [head]

Created 3 Django apps: Tasks, Manager, Employees.
Note: most of the files are auto-generated."
3. In regard to the flake8 errors - when fixing it, I think it will be better to add some dummy code (rather than comment out the lines)

**Review by orzionpour — CHANGES_REQUESTED** [review]
1. Commits should be squashed.

2. I would add to the description an explanation about what's going on in here.
Maybe something like

```
Created Django apps [head]

Created 3 Django apps: Tasks, Manager, Employees.
Note: most of the files are auto-generated.
```

3. In regard to the flake8 errors - when fixing it, I think it will be better to add some dummy code (rather than comment out the lines)

**Comment by mgold1234** [comment]
please fix all flake8 errors:

./Manager/models.py:1:1: F401 'django.db.models' imported but unused
./Manager/views.py:1:1: F401 'django.shortcuts.render' imported but unused
./Manager/tests.py:1:1: F401 'django.test.TestCase' imported but unused
./Manager/admin.py:1:1: F401 'django.contrib.admin' imported but unused
./Task/models.py:1:1: F401 'django.db.models' imported but unused
./Task/views.py:1:1: F401 'django.shortcuts.render' imported but unused
./Task/tests.py:1:1: F401 'django.test.TestCase' imported but unused
./Task/admin.py:1:1: F401 'django.contrib.admin' imported but unused
./Employees/models.py:1:1: F401 'django.db.models' imported but unused
./Employees/views.py:1:1: F401 'django.shortcuts.render' imported but unused
./Employees/tests.py:1:1: F401 'django.test.TestCase' imported but unused
./Employees/admin.py:1:1: F401 'django.contrib.admin' imported but unused
Error: Process completed with exit code 1.

**Comment by orzionpour** [comment]
I think that we should also add automation for the migrations.

**Pull request closed without merging**
