### PR TITLE
Add homepage & login

### LINKED ISSUE #24: Adding Login page
Move the login page to the users app.
- [ ] create templates folder for the users app
- [ ] moving login page to users app
- [ ] configure login page url to /login
- [ ] add homepage in falcon templates

Check out https://github.com/AvivLiberman/falcon/tree/new-login-page for nice and clean CSS and HTML if you want to 😉

### PR DESCRIPTION
**Pull request by orzionpour**
- [x] Add homepage
- [x] Add login page
- [x] Add favicons
- [x] Change first redirection to homepage
- [x] Change login view to use default django's auth view.

Resolves #24 

Co-Authored-By: Aviv Liberman <45610501+AvivLiberman@users.noreply.github.com>

### CODE REVIEW

**Review by aradz1997 — CHANGES_REQUESTED** [review]
Please wait for my PR to be merged

**Comment by mgold1234** [comment]
@aradz1997 why or need to wait for your until it merge?

**Comment by aradz1997** [comment]
@mgold1234 because the "apps" folder we made for the apps(users ,tasks) caused problems, I'm changing the structure of the files now and it will affect everything

**Comment by orzionpour** [comment]
After today's lecture, there are a few required changes. I'm on it.

**Comment by orzionpour** [comment]
On second thought, do we really need to change files according to yesterday's lecture at this part of the develompent? I mean to add the template inheritance and Django's forms ?
It's not one of the requirements for the upcoming demo and we are on a tight schedule already.
@natifridman @mgold1234 @kobihk @nunnatsa

**Review by AvivLiberman — APPROVED** [review]
I think you should not use django template blocks for now, we want to show something that works on Sunday.

**Review by Asafh7 — APPROVED** [review]

**Pull request merged**
