### PR TITLE
Divide project to apps

### LINKED ISSUE #23: Organize project's structure
@Asafh7
Please follow this structure: https://studygyaan.com/django/best-practice-to-structure-django-project-directories-and-files
The apps:
1. manager
2. employee
3. task
4. users
5. login

All the rest should be the same according the guide.

### PR DESCRIPTION
**Pull request by AvivLiberman**
We only need 2 apps for now: users, tasks. So I created the apps and put them in apps folder.
I think that this PR is only to create our work environment so each one could start writing the models.
The admin panel will help you to see the models you have created - after migrate. That a nice way to check your process 💪 
The things I did:
- created 2 new apps: users, tasks
- added auto migrate to setup.sh
- added admin panel with admin user
- moved images to img folder and changed the readme accordingly

To get the admin username and password please contact me.

Resolve #23 #18

### CODE REVIEW

**Comment by AvivLiberman** [comment]
@aradz1997 @avraham1992 @orzionpour @asafh7 @mgold1234 @natifridman @kobihk @nunnatsa
Can someone review my code?

**Comment by orzionpour** [comment]
LGTM.
I'll approve after we all confirm, on the zoom meeting later today., this is the right structure.

**Comment by orzionpour** [comment]
LGTM.
I'll approve if we all confirm, on the zoom meeting later today, this is the right structure.

**Comment by avraham1992** [comment]
I do not see that you have added the configurations in th settings..but looks good !

**Comment by AvivLiberman** [comment]
@avraham1992 check out [here](https://github.com/redhat-beyond/falcon/pull/35/files#diff-a83b84779047d2ac1c2e0642e4bf20a992212c9fb633b8bf9f4950d9a44b741bR42). Is that what you missed?

**Comment by avraham1992** [comment]
@AvivLiberman It does not work that way .. owe the copy from the page of app

**Review by avraham1992 — APPROVED** [review]

**Review by avraham1992 — APPROVED** [review]

**Review by Asafh7 — APPROVED** [review]

**Review by nunnatsa — APPROVED** [review]

**Pull request merged**
