### PR TITLE
Fix navbar

### LINKED ISSUE #109: Display username on nav bar
## Expected Behavior
Once a user is logged in, display its username on the right side of the navbar, with the 'logout' button to the left/right.

## Actual Behavior
The username isn't displayed, and the logout button aligned to the left of the navbar.

### PR DESCRIPTION
**Pull request by avraham1992**
Fixes #109 #115
## Changes you made

-fix navbar 
-add uesr name after the login

### CODE REVIEW

**Comment by AvivLiberman** [comment]
Please squash all your commits

**Comment by avraham1992** [comment]
> Please squash all your commits

its the same like befor .. how you do thes befor (tow weeks+/-)?

**Comment by AvivLiberman** [comment]
> > Please squash all your commits
> 
> its the same like befor .. how you do thes befor (tow weeks+/-)?

But we set together and fixed it for you, that means you worked in the wrong place

**Comment by avraham1992** [comment]
> > > Please squash all your commits
> > 
> > 
> > its the same like befor .. how you do thes befor (tow weeks+/-)?
> 
> But we set together and fixed it for you, that means you worked in the wrong place

no i am in the same place ..

**Pull request closed without merging**
