### PR TITLE
New homepage and login page moved to users app

### LINKED ISSUE #24: Adding Login page
Move the login page to the users app.
- [ ] create templates folder for the users app
- [ ] moving login page to users app
- [ ] configure login page url to /login
- [ ] add homepage in falcon templates

Check out https://github.com/AvivLiberman/falcon/tree/new-login-page for nice and clean CSS and HTML if you want to 😉

### PR DESCRIPTION
**Pull request by AvivLiberman**
- moved login page to users app
- added new homepage
- added routes from homepage to login
- added favicon folder with images for future templates

Fixed #24

### CODE REVIEW

**Review by orzionpour — CHANGES_REQUESTED** [review]
Well.... this PR basically discards any changes I made on my previous PR regards this issue (?), even though I'm still working on it.

As for the CR:
- The text on the bottom of homepage is getting cut off (you can see the whole text with 90% zoom, maybe it's issue with my browser, I'm not sure).
- For the login form: I guess we should use django framework for forms as we did on the first challenge.
- What's the use of favicon? Couldn't find it anywhere in the code.

**Comment by AvivLiberman** [comment]
@orzionpour That's exactly why you one of the reviewer here.

- favicon - I haven't figure out how to make it works so I just added the pictures for now.
- About the homepage I will have to check it

**This PR can get you a head start with your work, I didn't mean to do something instead of you**
***I can close it and you can pull this branch***

**Comment by orzionpour** [comment]
Cool, I'll take it from here. Thanks ✌️

**Comment by mgold1234** [comment]
@AvivLiberman , please change the commit message and use the imperative mood in the subject line
you can see the seven rules of a great Git commit message
https://chris.beams.io/posts/git-commit/

**Review by Asafh7 — APPROVED** [review]

**Comment by orzionpour** [comment]
Closed.
Moved to #55.

**Pull request closed without merging**
