### PR TITLE
fix flake8 errors

### LINKED ISSUE #17: CI fails with flake8 warnings
After adding flake8 check in the CI, this check is fails for several syntax errors in existing files.

```
./falcon/urls.py:23:19: E203 whitespace before ','
./falcon/urls.py:23:20: E231 missing whitespace after ','
./falcon/views.py:3:1: E302 expected 2 blank lines, found 1
./falcon/views.py:4:41: W292 no newline at end of file
```

### PR DESCRIPTION
**Pull request by AvivLiberman**
Resolve #17

### CODE REVIEW

**Comment by AvivLiberman** [comment]
https://github.com/redhat-beyond/falcon/issues/17

**Comment by AvivLiberman** [comment]
#17

**Comment by AvivLiberman** [comment]
@avraham1992 @orzionpour @mgold1234

**Review by mgold1234 — COMMENTED** [review]
lgtm

**Review by orzionpour — APPROVED** [review]
LGTM

**Comment by AvivLiberman** [comment]
@mgold1234 - got 2 reviews approved, can you merge it. I want that @orzionpour's PR will be green 😉

**Pull request merged**
