### PR TITLE
Add tasks filters features

### LINKED ISSUE #104: Add tasks filters features
First, note it is related to #93, #94 .

After creating the default user view, there should be added 2 filters:

- [ ] Filter by status
- [x] Filter by priority

Feel free to add any filter you think is relevant.

### PR DESCRIPTION
**Pull request by Asafh7**
Added task priority filter

Fixes #104
## Changes you made

-Added task priority filter function.

### CODE REVIEW

**Comment by natifridman** [comment]
@Asafh7 Please link it to an issue

**Comment by Asafh7** [comment]
> @Asafh7 Please link it to an issue
I think @orzionpour can do this, because he opened the issue, I don't have permission.

**Comment by orzionpour** [comment]
> > @Asafh7 Please link it to an issue
> > I think @orzionpour can do this, because he opened the issue, I don't have permission.

You need to edit your PR description and add the following: `Fixes #104'

**Review by avraham1992 — APPROVED** [review]

**Comment by orzionpour** [comment]
@Asafh7 
#104 indicates that the feature of filtering tasks by priority/status should be implemented here,
that is, a button (or something else) that should initiate this process and display the filtered tasks on the Tasks view.

**Review by orzionpour — CHANGES_REQUESTED** [review]
@Asafh7 
#104 indicates the need for a feature of filtering tasks by priority/status. That is, a button (or something clickable) that should initiate this process should be implemented here.

How I see it (just a suggestion, don't limit yourself according to the below implementation):
A text label "Filter by:", and a dropdown list should be implemented as the "front" here.
The dropdown should hold "priority", "status" and any other filter.
As for the "back" part - choosing one of the dropdown options (let say "status", for example) updates the tasks lists, call the already implemented filters in the Task model and display the filtered list.

**Pull request closed without merging**
